### PR TITLE
chore: update privacy terms with p2p info

### PR DESCRIPTION
**Pull request by AdrianAndersen**

### CODE REVIEW

**Comment by AdrianAndersen** [comment]
[Legg til i Privacy Policy at vi kan dele telefonnummer med andre elever for P2P](https://trello.com/c/bNyVIEHh/676-legg-til-i-privacy-policy-at-vi-kan-dele-telefonnummer-med-andre-elever-for-p2p)

**Comment by LarsSelbekk** [comment]
Is this just testing data or is it what's actually shown? In the latter case, we need to update the change date

**Review by LarsSelbekk — CHANGES_REQUESTED** [review]
> Is this just testing data or is it what's actually shown? In the latter case, we need to update the change date
I've looked at it, and not only is the change date outdated, but the entire thing should really be copied and dated like was done previously. Otherwise, you should remove the previous old version, because right now you're saying that all orders made from that date in 2021 consented to phone number sharing.

**Comment by AdrianAndersen** [comment]
We do not need this anymore

**Pull request closed without merging**
